[package]
name = "music-man"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
ratatui = "0.30.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
thiserror = "2.0.17"
